#pragma once

#pragma pack(1)
typedef struct _NETFILTERRULES 
{
	UCHAR	bAction;
	UCHAR	bUserRule;
	ULONG	dwIPFrom;
	ULONG	dwIPTo;
	USHORT	wLocalPortFrom;
	USHORT	wLocalPortTo;
	USHORT	wRemotePortFrom;
	USHORT	wRemotePortTo;
	WCHAR	szRuleName[100];
} NETFILTERRULE, *PNETFILTERRULE;
#pragma pack()

#pragma pack(1)
typedef struct _drv_request
{
	int result;
	int Inbound;
	ULONG struct_size;
	UINT64 pid;
	UINT32 localAddr;
	UINT32 remoteAddr;
	UINT16 localPort;
	UINT16 remotePort;
	union
	{
		HANDLE	hCompleteHandle;
		ULONG64	ulPad;
	};
}drv_request;
#pragma pack()

#pragma pack(1)
typedef struct _APP_ALBL_LIST
{
	union
	{
		LIST_ENTRY	ListEntry;
		BYTE		byPad[16];
	};
	UCHAR		bAction;	
	ULONG		dwProcessId;
	WCHAR		szFileName[MAX_PATH];
}APP_ALBL_LIST, *PAPP_ALBL_LIST;
#pragma pack()

#pragma pack(1)
typedef struct _URLDATA 
{
	union
	{
		LIST_ENTRY	ListEntry;
		BYTE		byPad[16];
	};
	UCHAR		bUserRule;
	UCHAR		bTypeOfEntry;
	WCHAR		szPatternName[100];
}URLDATA, *PURLDATA;
#pragma pack()

#pragma pack(1)
typedef struct _SITERULE
{
	union
	{
		LIST_ENTRY	ListEntry;
		BYTE		byPad[16];
	};
	UCHAR		bState;
	UCHAR		bMatch;
	UCHAR		bSession;
	UCHAR		bPermanent;
	UCHAR		bThirdParty;
	UCHAR		bReferer;
	UCHAR		bADS;
	UCHAR		bJScript;
	UCHAR		bVbScript;
	UCHAR		bActiveX;
	UCHAR		bPopups;
	WCHAR		szDomain[100];
}SITERULE, *PSITERULE;
#pragma pack()

#pragma pack(1)
typedef struct _APPASKINFO
{
	UCHAR	bDirection;
	char	szAddFrom[100];
	char	szAddTo[100];
	USHORT	wPortFrom;
	USHORT	wPortTo;
	char	szProcessName[MAX_PATH];
}APPASKINFO, *PAPPASKINFO;
#pragma pack()

#pragma pack(1)
typedef enum _TYPE_OF_ENTRY
{
	ENTRY_TYPE_DOMAIN = 0,
	ENTRY_TYPE_SUBSTRING = 1
}TYPE_OF_ENTRY;
#pragma pack()

#pragma pack(1)
typedef struct _NETWORK_BLOCK
{
	LIST_ENTRY		ListEntry;
	ULONG			ulLocalAddress;
	USHORT			usLocalPort;
	ULONG			ulDestinationAddress;
	USHORT			usDestinationPort;
	USHORT			usDirection;
	BOOLEAN			IsLocalPortConnect;
	LARGE_INTEGER	llStartTime;
	LONGLONG		llEndTime;
	ULONG			ulProcessId;
	BOOLEAN			IsBlocked;
}NETWORK_BLOCK,*PNETWORK_BLOCK;
#pragma pack()


#define IOCTL_PAUSE_NETFILTER				CTL_CODE(FILE_DEVICE_NETWORK, 0x900, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_RESUME_NETFILTER				CTL_CODE(FILE_DEVICE_NETWORK, 0x901, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_NETFILTER_RULE			CTL_CODE(FILE_DEVICE_NETWORK, 0x902, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CLEAR_ALL_NETFILTER_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x903, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_BLOCK_ALL_NETFILTER_TRAFFIC	CTL_CODE(FILE_DEVICE_NETWORK, 0x904, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CMD_GETREQUEST				CTL_CODE(FILE_DEVICE_NETWORK, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CMD_FILTER_REPLY				CTL_CODE(FILE_DEVICE_NETWORK, 0x911, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PAUSE_APPMONITOR				CTL_CODE(FILE_DEVICE_NETWORK, 0x920, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_RESUME_APPMONITOR				CTL_CODE(FILE_DEVICE_NETWORK, 0x921, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_APPLICATION_RULE	CTL_CODE(FILE_DEVICE_NETWORK, 0x930, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_DEFAULT_APPLICATION_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x931, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_APPLICATION_MONITOR		CTL_CODE(FILE_DEVICE_NETWORK, 0x932, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_PHISHING_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x940, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_PHISHING_RULE				CTL_CODE(FILE_DEVICE_NETWORK, 0x941, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_PHISHING_MONITOR		CTL_CODE(FILE_DEVICE_NETWORK, 0x942, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_ANTIBANNER_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x950, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_ANTIBANNER_RULE			CTL_CODE(FILE_DEVICE_NETWORK, 0x951, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_ANTIBANNER_MONITOR		CTL_CODE(FILE_DEVICE_NETWORK, 0x952, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_WEBFILTER_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x960, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_WEBFILTER_RULE			CTL_CODE(FILE_DEVICE_NETWORK, 0x961, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_WEBFILTER_MONITOR		CTL_CODE(FILE_DEVICE_NETWORK, 0x962, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_WEBAPP_RULE			CTL_CODE(FILE_DEVICE_NETWORK, 0x970, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_WEBAPP_RULE				CTL_CODE(FILE_DEVICE_NETWORK, 0x971, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_WEBAPP_MONITOR			CTL_CODE(FILE_DEVICE_NETWORK, 0x972, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_WEBSITE_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x980, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_WEBSITE_RULE				CTL_CODE(FILE_DEVICE_NETWORK, 0x981, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_WEBSITE_MONITOR			CTL_CODE(FILE_DEVICE_NETWORK, 0x982, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CLEAR_ALL_PC_WEBSITE_RULE		CTL_CODE(FILE_DEVICE_NETWORK, 0x1000, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_ADD_PC_WEBSITE_RULE			CTL_CODE(FILE_DEVICE_NETWORK, 0x1001, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_START_PC_WEBSITE_MONITOR		CTL_CODE(FILE_DEVICE_NETWORK, 0x1002, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

