#pragma once

#define UTL_MAX_PATH		1024
#define UTL_MAX_REC_LEVEL	25
#define	BY_UTL_DB			1
#define	BY_UTL_POLY			2

const DWORD UTL_OPT_INFECTION_FOUND = 0x01;
const DWORD UTL_OPT_INFECTION_CLEAN = 0x02;
const DWORD UTL_OPT_INFECTION_FAIL = 0x03;
const DWORD UTL_OPT_INFECTION_SKIP = 0x04;
const DWORD UTL_OPT_INFECTION_FOUND_MEM = 0x05;
const DWORD UTL_OPT_INFECTION_THREAD_FOUND = 0x06;
const DWORD UTL_OPT_INFECTION_THREAD_FIXED = 0x07;
const DWORD UTL_OPT_INFECTION_THREAD_FAILED = 0x08;
const DWORD UTL_OPT_INFECTION_HANDLE_REMOVED = 0x09;
const DWORD UTL_OPT_INFECTION_HANDLE_FAILED = 0x0A;
const DWORD UTL_OPT_INFECTION_HANDLE_FOUND = 0x0B;
const DWORD UTL_OPT_INFECTION_HOOKS_FOUND = 0x0C;

const DWORD	UTL_OPT_THREAD = 0x01;	
const DWORD	UTL_OPT_MEM_PROCESS = 0x02;
const DWORD	UTL_OPT_FILE = 0x03;
const DWORD	UTL_OPT_HANDLE = 0x04;
const DWORD	UTL_OPT_HOOK = 0x05;
const DWORD	UTL_OPT_MAIN_STATUS = 0x06;
const DWORD	UTL_OPT_SUB_STATUS = 0x07;

const DWORD UTL_OPT_SKIP_TIME = 20000;
